### PR TITLE
Update DatbaseUserProvider.php to add missing method

### PR DESCRIPTION
**Pull request by designvoid**
The getModel method was missing and caused issues with some additional packages.

### CODE REVIEW

**Comment by stevebauman** [comment]
What packages in particular is this an issue with?

**Comment by designvoid** [comment]
wildside/userstamps was the one that threw it up initially but I would have
to go back and check on the other ones.

**Comment by designvoid** [comment]
Has this code been removed from master?

**Comment by stevebauman** [comment]
@designvoid Yes it was. I implemented a `__call` method that will call upon the underlying `EloquentUserProvider` for missing methods.

This is actually an issue with that package, not Adldap2.

They're assuming the method is there, when it adheres to no contract:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Contracts/Auth/UserProvider.php

https://github.com/WildSideUK/Laravel-Userstamps/blob/master/src/Userstamps.php#L110-L122

**Pull request merged**
