### PR TITLE
Master

### PR DESCRIPTION
**Pull request by candradebh**
Fix error integer validation

### CODE REVIEW

**Comment by stevebauman** [comment]
When do you receive this error?

**Comment by darthtaco** [comment]
FYI, I am attempting to upgrade from Adldap2 2.1 to 3.0 and I am receiving the error that I believe this PR was intended to fix.  This happens during authentication attempt.

image 10

Laravel 5.2.45
Adldap2 v7.0.14
Adldap2-laravel v3.0.4

If I change my `config/adldap.php` file to avoid using the `env()` function when setting the port (and set it to an integer directly) then the error goes away.  My `.env` file does not have quotes around the port setting.

**Comment by stevebauman** [comment]
Hi @darthtaco, ok I'll fix this in master. I've never needed to set my port setting in my `.env`, so that explains why I've never seen this error. Also never received a response from the PR author, so it seemed like a unique issue with their application.

**Comment by darthtaco** [comment]
Understood @stevebauman, thanks.

**Comment by stevebauman** [comment]
Hi @darthtaco, this is fixed in the root Adldap2 repository. Please update using `composer update` and you should no longer receive this issue. Thanks!

**Comment by darthtaco** [comment]
Great!!  I've confirmed that this has resolved the issue in my environment. Many thanks.

**Pull request closed without merging**
