### PR TITLE
mYEmaIl@sampeS.oRg to myemail@samples.org

### PR DESCRIPTION
**Pull request by xvlady**
This is a bad change.
but I do not know how to do better.

### CODE REVIEW

**Comment by stevebauman** [comment]
Hi @xvlady, I wouldn't call it a bad change, I'm just not sure if this may have repercussions to other users who may rely on case-sensitivity. I'll see if there's another way we can implement this for specific use cases such as yours.

**Comment by stevebauman** [comment]
Actually, this is already implemented, you can create a sync attribute callback to do this:

https://github.com/Adldap2/Adldap2-Laravel#sync-attribute-callbacks

```php
'sync_attributes' => [
    'email' => 'App\Handlers\LdapAttributeHandler@email'
]
```

```php
namespace App\Handlers;

use Adldap\Models\User;

class LdapAttributeHandler
{
    public function email(User $user)
    {
        return strtolower($user->getEmail());
    }
}
```

**Comment by xvlady** [comment]
where($username='xVlady') 
User not'fond!
in table value - xvlady

**Comment by stevebauman** [comment]
Shoot you're right, while you can customize synced attributes, searching will still be case-sensitive...

Going to see what I can do.

**Comment by xvlady** [comment]
sync from UsernameAttribute

**Pull request closed without merging**
