### PR TITLE
BindsLdapUserModel - Laravel 5.8

### PR DESCRIPTION
**Pull request by andrefigueira93**
### **File Being Edited =>** Adldap\Laravel\Listeners\BindsLdapUserModel

> In Laravel 5.8 i have had to change from 

```
public function handle($event)
    {
        if (
            $this->isUsingAdldapProvider($event->guard)
            && $this->canBind($event->user)
            && $user = Resolver::byModel($event->user)
        ) {
            $event->user->setLdapUser($user);
        }
    }

    protected function isUsingAdldapProvider($guard) : bool
    {
        return Auth::guard($guard)->getProvider() instanceof DatabaseUserProvider;
    }
```

### **to**

```
public function handle($event)
    {
        if (
            $this->isUsingAdldapProvider()
            && $this->canBind($event->user)
            && $user = Resolver::byModel($event->user)
        ) {
            $event->user->setLdapUser($user);
        }
    }

    protected function isUsingAdldapProvider() : bool
    {
        return Auth::guard()->getProvider() instanceof DatabaseUserProvider;
    }
```

Unique way that works

### CODE REVIEW

**Comment by stevebauman** [comment]
Hi @andrefigueira93, I don't think this change would resolve the issue you're having.

The `Authenticated` and `Login` events both have the `$guard` property set to the name of the guard that your user is authenticated with. This property allows us to locate the correct guard and ensure you're using an Adldap2 provider with it so no exceptions are generated.

**Authenticated Event:**
https://github.com/laravel/framework/blob/cd7486a4355be57e8928f89048a25f30883f202f/src/Illuminate/Auth/Events/Authenticated.php#L16

**Login Event:**
https://github.com/laravel/framework/blob/cd7486a4355be57e8928f89048a25f30883f202f/src/Illuminate/Auth/Events/Login.php#L16

What is the guard property set to on the `Login` and `Authenticated` events?

**Comment by andrefigueira93** [comment]
Reproduction of the error
Captura de Tela 2019-03-21 às 11 32 52

The problem is here -> dd($event)
Captura de Tela 2019-03-21 às 11 36 36

The `$event` doesn't have the `->guard` object.

`Auth::guard()->getProvider() instanceof DatabaseUserProvider` is enough to verify.

**Comment by stevebauman** [comment]
Strange, are you sure you're using Laravel 5.8?

This is definitely a bug though, I thought the `$guard` property was available for Laravel 5.5 or greater, but it's only available on Laravel 5.7 or greater.

Going to patch this now, thanks @andrefigueira93!

**Comment by andrefigueira93** [comment]
Tried in 5.6, 5.7 and 5.8  =/ all of them are reproducing this error =/

You're welcome! I'm here to help =)

**Comment by stevebauman** [comment]
Are you sure you're using those versions? I'm using v6.0 model binding in 5.7 and 5.8 and don't receive this exception.

**Pull request closed without merging**
