### PR TITLE
Remove the extra call to the ldap server

### PR DESCRIPTION
**Pull request by valenman**

### CODE REVIEW

**Comment by stevebauman** [comment]
Not sure what this is doing? The `$default` parameter in the `Config::get($item, $default);` already accomplishes this. There's no call going on to the LDAP server.

**Comment by valenman** [comment]
not quite as well. `Configuration::get($item, $default);` will compute both values of `$item` and `$default`. In that situation I wanted to fix the calculation of default values occurs only when required.

**Comment by stevebauman** [comment]
> will compute both values of `$item` and `$default`

I don't think the extra call to the schema object is causing that much of a performance issue,

Do you have any benchmarks to provide evidence that this is the case?

**Comment by valenman** [comment]
I will describe my problem. method ldap_bind takes me quite a long time and I would like to reduce the application's queries to the ldap server. I was authenticated and saved in session user ID. In subsequent actions on this basis I ID library builds the user model in the method `AdldapAuthUserProvider::discoverAdldapFromMode`l and I don't understand why the library connects to the Ldap server when you only select a value from the database. one of the places where this occurs precisely in those methods where I made changes.

**Comment by stevebauman** [comment]
The `AdldapAuthUserProvider::discoverAdldapFromModel` method only performs a query on your LDAP server when you've enabled the `bind_user_to_model` configuration option.

**Pull request closed without merging**
